# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 00:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='expire_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
