# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20170513_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(0, 'VeryLow'), (1, 'Low'), (2, 'Normal'), (3, 'High'), (4, 'Very High')], default=0),
        ),
    ]
