# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='expire_date',
            field=models.DateField(default=''),
        ),
    ]
